//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTable
    {
        public int CardID { get; set; }
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public string CardImage { get; set; }
        public decimal CardMoney { get; set; }
        public byte CardLive { get; set; }
        public byte Synchronize { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<int> CDID { get; set; }
        public int UserID { get; set; }
        public Nullable<decimal> MoneyStart { get; set; }
        public Nullable<byte> CardShow { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
