//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZhuanTiTable
    {
        public int ZhuanTiID { get; set; }
        public string ZhuanTiName { get; set; }
        public string ZhuanTiImage { get; set; }
        public int UserID { get; set; }
        public byte ZhuanTiLive { get; set; }
        public byte Synchronize { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<int> ZTID { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
