using System;
using System.Text;

public partial class SexSpider_GetListData2 : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        StringBuilder result = new StringBuilder();
        result.Append("{");
        //start
        result.Append("list:[");
        //1. 好了KK
        result.Append("{\"siteid\":\"1\",\"siterank\":\"A01\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"好了KK se.haoav17.com\",\"listpage\":\"l-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://se.haoav17.com\",\"sitelink\":\"http://se.haoav17.com/listhtml/1.html\",\"liststart\":\"<divclass=\\\"list\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"title\\\">\",\"imageend\":\"<divclass=\\\"pagea\\\">\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //26. 插死她
        result.Append("{\"siteid\":\"26\",\"siterank\":\"A02\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"插死她 www.65zzzz.com\",\"listpage\":\"list_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.65zzzz.com\",\"sitelink\":\"http://www.65zzzz.com/p01/index.html\",\"liststart\":\"<divclass=\\\"typelist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divid=\\\"view1\\\"class=\\\"mtop\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/htm\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //3. 摸逼逼
        result.Append("{\"siteid\":\"3\",\"siterank\":\"A03\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"摸逼逼 www.mbbb33.com\",\"listpage\":\"(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.mbbb33.com\",\"sitelink\":\"http://www.mbbb33.com/mnv67/6/1.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=n_bd>\",\"imageend\":\"</div>\",\"oninclude\":\"/admrw\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //4. 爸爸嘿
        result.Append("{\"siteid\":\"4\",\"siterank\":\"A04\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"爸爸嘿 www.meimeihei.cc\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.meimeihei.cc\",\"sitelink\":\"http://www.meimeihei.cc/tupian/toupai/index.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=temp23>\",\"imageend\":\"</div>\",\"oninclude\":\"/tupian\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //5. AV天堂
        result.Append("{\"siteid\":\"5\",\"siterank\":\"A05\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"AV天堂 www.avttav2016.com\",\"listpage\":\"list_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.avttav2016.com\",\"sitelink\":\"http://www.avttav2016.com/zipaitoupai/index.html\",\"liststart\":\"<divclass=\\\"newslist\\\">\",\"listend\":\"<divclass=\\\"page\\\">\",\"imagestart\":\"<divid=\\\"text_novel\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/zipaitoupai\",\"notinclude\":\"\",\"pagestart\":\"<atitle=\\\"Page\\\">\",\"pageend\"=\"<div\"},");
        //24. 夜夜嘿
        result.Append("{\"siteid\":\"24\",\"siterank\":\"A06\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"夜夜嘿 yeyehei.cc\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://yeyehei.cc\",\"sitelink\":\"http://yeyehei.cc/pic/zipai/index.html\",\"liststart\":\"<divclass=\\\"idxnew\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/pic/zipai\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //9. 狠狠撸-自拍专区
        result.Append("{\"siteid\":\"9\",\"siterank\":\"A07\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"狠狠撸-自拍专区 www.279vv.com\",\"listpage\":\"index20_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.279vv.com\",\"sitelink\":\"http://www.279vv.com/html/part/index20.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"imagestart\":\"<divclass=content>\",\"imageend\":\"</div>\",\"oninclude\":\"/html/se\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //27. 狠狠撸-性爱自拍
        result.Append("{\"siteid\":\"27\",\"siterank\":\"A08\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"狠狠撸-性爱自拍 www.279vv.com\",\"listpage\":\"index43_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.279vv.com\",\"sitelink\":\"http://www.279vv.com/html/part/index43.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"imagestart\":\"<divclass=content>\",\"imageend\":\"</div>\",\"oninclude\":\"/html/se\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //7. 91Porn-原创申请
        result.Append("{\"siteid\":\"7\",\"siterank\":\"A09\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"原创申请 www.91porn.com\",\"listpage\":\"forumdisplay.php?fid=19&orderby=dateline&page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://91.t9d.club/\",\"sitelink\":\"http://91.t9d.club/forumdisplay.php?fid=19&orderby=dateline&page=1\",\"liststart\":\"<divid=\\\"threadlist\\\"\",\"listend\":\"</div>\",\"imagestart\":\"<divid=\\\"threadtitle\\\">\",\"imageend\":\"<divclass=\\\"postactions\\\">\",\"oninclude\":\"viewthread\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //12. 91Porn-我爱我妻
        result.Append("{\"siteid\":\"12\",\"siterank\":\"A10\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"我爱我妻 www.91porn.com\",\"listpage\":\"forumdisplay.php?fid=21&orderby=dateline&page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://91.t9d.club/\",\"sitelink\":\"http://91.t9d.club/forumdisplay.php?fid=21&orderby=dateline&page=1\",\"liststart\":\"<divid=\\\"threadlist\\\"\",\"listend\":\"</div>\",\"imagestart\":\"<divid=\\\"threadtitle\\\">\",\"imageend\":\"<divclass=\\\"postactions\\\">\",\"oninclude\":\"viewthread\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //8. 超碰在线视频
        result.Append("{\"siteid\":\"8\",\"siterank\":\"A11\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"超碰在线视频 44lang.com\",\"listpage\":\"albums?page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://44lang.com\",\"sitelink\":\"http://44lang.com/albums?page=1\",\"liststart\":\"<divclass=\\\"blinkp\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"imagestart\":\"<divid=\\\"album\",\"imageend\":\"<divclass=\\\"pagination\\\">\",\"oninclude\":\"/album\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"pagination\\\">\",\"pageend\"=\"</div>\"},");
        //22. 黑木耳基地
        result.Append("{\"siteid\":\"22\",\"siterank\":\"A12\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"黑木耳基地 www.u6f4.com\",\"listpage\":\"index-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.u6f4.com\",\"sitelink\":\"http://www.u6f4.com/AAtupian/AAtb/zipai/index.html\",\"liststart\":\"<divclass=\\\"boxlistchannel\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"post-bd\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/AAtupian\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //16. 精彩生活自拍汇
        result.Append("{\"siteid\":\"16\",\"siterank\":\"\",\"viplevel\":\"2\",\"ishided\":\"1\",\"sitename\":\"精彩生活自拍汇 bbs.we560.com【失效】\",\"listpage\":\"(*)\",\"pageencode\":\"gbk\",\"domain\":\"http://bbs.we560.com/xtu/\",\"sitelink\":\"http://bbs.we560.com/xtu\",\"liststart\":\"<divalign=center>\",\"listend\":\"</div>\",\"imagestart\":\"<table\",\"imageend\":\"</div>\",\"oninclude\":\"html/\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //17. 正妹写真套图
        result.Append("{\"siteid\":\"17\",\"siterank\":\"\",\"viplevel\":\"0\",\"ishided\":\"1\",\"sitename\":\"正妹写真套图 bbs.we560.com【失效】\",\"listpage\":\"(*)\",\"pageencode\":\"gbk\",\"domain\":\"http://bbs.we560.com/xz/cn\",\"sitelink\":\"http://bbs.we560.com/xz/cn\",\"liststart\":\"<divclass=\\\"viewbox\\\">\",\"listend\":\"</body>\",\"imagestart\":\"<divclass=\\\"img-show\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"<select\",\"pageend\"=\"</select>\"},");
        //6. 神马影院
        result.Append("{\"siteid\":\"6\",\"siterank\":\"\",\"viplevel\":\"2\",\"ishided\":\"1\",\"sitename\":\"神马影院 www.7771.me【失效】\",\"listpage\":\"index60_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.7771.me\",\"sitelink\":\"http://www.7771.me/nv/you/index60.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"n_bd\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/nv/so\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //23. Ady映画网
        result.Append("{\"siteid\":\"23\",\"siterank\":\"A13\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"Ady映画网 jj.6ady.info\",\"listpage\":\"New(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://jj.6ady.info\",\"sitelink\":\"http://jj.6ady.info/zjgx/New.html\",\"liststart\":\"<divclass=\\\"pre_b\\\">\",\"listend\":\"<divclass=\\\"pre_b_class_page\\\">\",\"imagestart\":\"<divclass=\\\"movie_c_pre\\\">\",\"imageend\":\"<divclass=\\\"movie_d\\\">\",\"oninclude\":\"/d\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //30. 女黄人
        result.Append("{\"siteid\":\"30\",\"siterank\":\"A14\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"女黄人www.av23.me【超快】\",\"listpage\":\"index60_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.av23.me\",\"sitelink\":\"http://www.av23.me/html/part/sseexx60.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //25. 久久热
        result.Append("{\"siteid\":\"25\",\"siterank\":\"A15\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"久久热 www.99qq1.com\",\"listpage\":\"(*)/\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.99qq1.com\",\"sitelink\":\"http://www.99qq1.com/albums/\",\"liststart\":\"<divclass=\\\"thumbsmodels\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"imagestart\":\"<divclass=\\\"models-slider-big\\\">\",\"imageend\":\"<divclass=\\\"models-slider-small\\\">\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //28. 就去路
        result.Append("{\"siteid\":\"28\",\"siterank\":\"A16\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"就去路 www.97luwang.com\",\"listpage\":\"10_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.97luwang.com\",\"sitelink\":\"http://www.97luwang.com/html/part/10.html\",\"liststart\":\"<divid=\\\"text_box\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //29. 色久久
        result.Append("{\"siteid\":\"29\",\"siterank\":\"A17\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"色久久 www.110pp.com\",\"listpage\":\"index27_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.110pp.com\",\"sitelink\":\"http://www.110pp.com/html/part/index27.html\",\"liststart\":\"<divid=\\\"text\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"novelContent\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //32. 第四色
        result.Append("{\"siteid\":\"32\",\"siterank\":\"A18\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"第四色 www.6666ak.com\",\"listpage\":\"23-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.6666ak.com\",\"sitelink\":\"http://www.6666ak.com/artlist/23.html\",\"liststart\":\"<divclass=\\\"atrlist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divid=\\\"postmessage\\\"class=\\\"t_msgfont\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/arts\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //33. 七次郎
        result.Append("{\"siteid\":\"33\",\"siterank\":\"A19\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"七次郎 www.7langtu.com【超快】\",\"listpage\":\"index_page_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.7langtu.com\",\"sitelink\":\"http://www.7langtu.com/pictures/6/index.html\",\"liststart\":\"<divclass=\\\"list-video\\\">\",\"listend\":\"<ulclass=\\\"pagination\\\">\",\"imagestart\":\"<divclass=\\\"ads_55\\\">\",\"imageend\":\"<divclass=\\\"end-list\\\">\",\"oninclude\":\"/picture\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //37. 色男网
        result.Append("{\"siteid\":\"37\",\"siterank\":\"\",\"viplevel\":\"2\",\"ishided\":\"1\",\"sitename\":\"色男网 www.q2233.com\",\"listpage\":\"forum-2-(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.q2233.com/\",\"sitelink\":\"http://www.q2233.com/forum-2-1.html\",\"liststart\":\"<divid=\\\"threadlist\",\"listend\":\"<divid=\\\"filter_special_menu\",\"imagestart\":\"<divclass=\\\"t_fsz\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"thread\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //2. 一焦进洞
        result.Append("{\"siteid\":\"2\",\"siterank\":\"A20\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"一焦进洞 www.yjjdo.pw\",\"listpage\":\"(*).jsp\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.yjjdo.pw\",\"sitelink\":\"http://www.yjjdo.pw/yjj2/6/1.jsp\",\"liststart\":\"<divclass=\\\"mainArea\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"picContent\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/yjj1\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //38. ♂爱AB♀
        result.Append("{\"siteid\":\"38\",\"siterank\":\"A21\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"♂爱AB♀ www.iabiab.com【超快】\",\"listpage\":\"list_10_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.iabiab.com\",\"sitelink\":\"http://www.iabiab.com/ws/list_10_1.html\",\"liststart\":\"<divclass=main>\",\"listend\":\"<divclass=dede_pages>\",\"imagestart\":\"<divclass=\\\"article_body\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/ws\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //39. 撸撸嘿
        result.Append("{\"siteid\":\"39\",\"siterank\":\"A22\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"撸撸嘿 www.luluhei.in【超快】\",\"listpage\":\"albums?page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.luluhei.in\",\"sitelink\":\"http://www.luluhei.in/albums?page=1\",\"liststart\":\"<divclass=\\\"container\\\">\",\"listend\":\"<divclass=\\\"list-group\\\">\",\"imagestart\":\"<divclass=\\\"col-md-8\\\">\",\"imageend\":\"<divclass=\\\"footer-container\\\">\",\"oninclude\":\"/album/\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //40. 开心五月
        result.Append("{\"siteid\":\"40\",\"siterank\":\"A23\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"开心五月 www.ppcao66.com\",\"listpage\":\"index9_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.ppcao66.com\",\"sitelink\":\"http://www.ppcao66.com/html/part/index9.html\",\"liststart\":\"<ulclass=\\\"textList\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"novelContent\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //41. 夜夜撸
        result.Append("{\"siteid\":\"41\",\"siterank\":\"A24\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"夜夜撸 www.73eg.com\",\"listpage\":\"19_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.73eg.com\",\"sitelink\":\"http://www.73eg.com/html/part/19.html\",\"liststart\":\"<divclass=\\\"list\\\">\",\"listend\":\"<divclass=\\\"page\\\">\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"<liclass=\\\"last\\\">\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        ////////////////////////////////////////////////////////////////////////////VIP分隔线////////////////////////////////////////////////////////////////////////////
        //34. 福利图片
        result.Append("{\"siteid\":\"34\",\"siterank\":\"B09\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"福利图片 www.dongde.in【超快】\",\"listpage\":\"page/(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.dongde.in\",\"sitelink\":\"http://www.dongde.in/category/福利图片/\",\"liststart\":\"<divclass=\\\"content\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"imagestart\":\"<articleclass=\\\"article-content\\\">\",\"imageend\":\"</article>\",\"oninclude\":\"http://dongde.in/post\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"page\\\">\",\"pageend\"=\"...\"},");
        //35. 街拍美女
        result.Append("{\"siteid\":\"35\",\"siterank\":\"B10\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"街拍美女 www.dongde.in【超快】\",\"listpage\":\"page/(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.dongde.in\",\"sitelink\":\"http://www.dongde.in/category/街拍美女/\",\"liststart\":\"<divclass=\\\"content\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"imagestart\":\"<articleclass=\\\"article-content\\\">\",\"imageend\":\"</article>\",\"oninclude\":\"http://dongde.in/post\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"page\\\">\",\"pageend\"=\"...\"},");
        //36. 狠狠撸-街拍图区
        result.Append("{\"siteid\":\"36\",\"siterank\":\"B11\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"狠狠撸-街拍图区 www.279vv.com\",\"listpage\":\"index43_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.279vv.com\",\"sitelink\":\"http://www.279vv.com/html/part/index44.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"imagestart\":\"<divclass=content>\",\"imageend\":\"</div>\",\"oninclude\":\"/html/se\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //31. 中国人体艺术
        result.Append("{\"siteid\":\"31\",\"siterank\":\"B01\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"中国人体艺术 www.rt114.org\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.rt114.org\",\"sitelink\":\"http://www.rt114.org/zg/index.html\",\"liststart\":\"<divclass=\\\"main\\\">\",\"listend\":\"<div>\",\"imagestart\":\"<divclass=\\\"picbox\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http://www.rt114.org/html\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"page\\\">\",\"pageend\"=\"...\"},");
        //10. 1000人体
        result.Append("{\"siteid\":\"10\",\"siterank\":\"B06\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"1000人体 www.1000rtrt.com\",\"listpage\":\"index(*).htm\",\"pageencode\":\"gbk\",\"domain\":\"http://www.1000rtrt.com\",\"sitelink\":\"http://www.1000rtrt.com/yzrt/index.htm\",\"liststart\":\"<body\",\"listend\":\"</center>\",\"imagestart\":\"<p\",\"imageend\":\"<table\",\"oninclude\":\"/News\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //11. 人体艺术
        result.Append("{\"siteid\":\"11\",\"siterank\":\"\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"人体艺术 www.68s.net【失效】\",\"listpage\":\"list_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.68s.net\",\"sitelink\":\"http://www.68s.net/list/zhongguorenti/list_1.html\",\"liststart\":\"<divclass=\\\"list\\\">\",\"listend\":\"<divclass=\\\"pages\\\">\",\"imagestart\":\"<divclass=\\\"imgbox\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"pages\\\">\",\"pageend\"=\"</div>\"},");
        //13. 妹子图
        result.Append("{\"siteid\":\"13\",\"siterank\":\"B03\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"妹子图 www.mzitu.com【超快】\",\"listpage\":\"(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.mzitu.com\",\"sitelink\":\"http://www.mzitu.com/page/1\",\"liststart\":\"<divclass=\\\"postlist\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"main-image\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"pagenavi\",\"pageend\"=\"</div>\"},");
        //14. 猫扑炫图
        result.Append("{\"siteid\":\"14\",\"siterank\":\"B04\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"猫扑炫图 tt.mop.com\",\"listpage\":\"list_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://tt.mop.com\",\"sitelink\":\"http://tt.mop.com/xuan/list_1.html\",\"liststart\":\"<divclass=\\\"main\",\"listend\":\"<divclass=\\\"page\",\"imagestart\":\"<divclass=\\\"txtmod\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http://tt\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //15. ZOL人像摄影
        result.Append("{\"siteid\":\"15\",\"siterank\":\"B05\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"ZOL人像摄影 bbs.zol.com.cn\",\"listpage\":\"d16_pic_new_p(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://bbs.zol.com.cn\",\"sitelink\":\"http://bbs.zol.com.cn/dcbbs/d16_pic_new_p1.html\",\"liststart\":\"id=\\\"picBookList\\\"\",\"listend\":\"</ul>\",\"imagestart\":\"<divid=\\\"bookContent\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/dcbbs\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //18. 黑丝网
        result.Append("{\"siteid\":\"18\",\"siterank\":\"\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"黑丝网 www.heisiwang.com【失效】\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.heisiwang.com\",\"sitelink\":\"http://www.heisiwang.com/xinggan/index.html\",\"liststart\":\"<divclass=\\\"channel-ctn\\\">\",\"listend\":\"<divclass=\\\"pages\\\">\",\"imagestart\":\"<divclass=\\\"endtext\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/pic\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\"},");
        //19. 爱人体
        result.Append("{\"siteid\":\"19\",\"siterank\":\"B07\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"爱人体 www.kanrenti.org\",\"listpage\":\"(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.kanrenti.org/yazhourenti/\",\"sitelink\":\"http://www.kanrenti.org/yazhourenti/index.html\",\"liststart\":\"<divclass=\\\"lm\\\">\",\"listend\":\"<ulclass=\\\"page\\\"\",\"imagestart\":\"<ulclass=\\\"file\\\">\",\"imageend\":\"</ul>\",\"oninclude\":\"20\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"photo\",\"pageend\"=\"</ul>\"},");
        //20. 漂漂美术馆
        result.Append("{\"siteid\":\"20\",\"siterank\":\"B08\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"漂漂美术馆 www.ppmsg.net\",\"listpage\":\"(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.ppmsg.net/jiepaimeinv/\",\"sitelink\":\"http://www.ppmsg.net/jiepaimeinv/index.html\",\"liststart\":\"<divclass=\\\"lm\\\">\",\"listend\":\"<ulclass=\\\"page\\\"\",\"imagestart\":\"<divid=\\\"imagelist\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"20\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"image\\\">\",\"pageend\"=\"</ul>\"},");
        //21. 人体艺术
        result.Append("{\"siteid\":\"21\",\"siterank\":\"B02\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"人体艺术 www.rentiyishu88.org\",\"listpage\":\"(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.rentiyishu88.org/rentiwaipai/\",\"sitelink\":\"http://www.rentiyishu88.org/rentiwaipai/index.html\",\"liststart\":\"<divclass=\\\"lm\\\">\",\"listend\":\"<ulclass=\\\"page\\\"\",\"imagestart\":\"<ulclass=\\\"file\\\">\",\"imageend\":\"</ul>\",\"oninclude\":\"20\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"photo\",\"pageend\"=\"</ul>\"}");
        //end
        result.Append("]}");

        Response.Write(result.ToString());
        Response.End();
    }
}