using System;
using System.Text;

public partial class SexSpider_GetListData3 : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        StringBuilder result = new StringBuilder();

        //start
        result.Append("{\"site_list\":[");
        //1. 好了KK
        result.Append("{\"siteid\":\"1\",\"siterank\":\"A01\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"好了KK\",\"listpage\":\"1-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://se.haoav30.com\",\"sitelink\":\"http://se.haoav30.com/listhtml/1.html\",\"liststart\":\"<divclass=\\\"list\\\">\",\"listend\":\"</div>\",\"listdiv\":\"div.list ul li a\",\"imagestart\":\"<divclass=\\\"title\\\">\",\"imageend\":\"<divclass=\\\"pagea\\\">\",\"imagediv\":\"div.main img\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //26. 激情五月
        result.Append("{\"siteid\":\"26\",\"siterank\":\"A02\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"激情五月【快速】\",\"listpage\":\"list_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.42pj.com\",\"sitelink\":\"http://www.42pj.com/p01/index.html\",\"liststart\":\"<divclass=\\\"typelist\\\">\",\"listend\":\"</div>\",\"listdiv\":\"div.typelist ul li a\",\"imagestart\":\"<divid=\\\"view1\\\"class=\\\"mtop\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.mtop img\",\"oninclude\":\"/htm\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //3. 摸逼逼
        result.Append("{\"siteid\":\"3\",\"siterank\":\"A03\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"摸逼逼\",\"listpage\":\"(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.mbbb33.com\",\"sitelink\":\"http://www.mbbb33.com/mnv67/6/1.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"listdiv\":\"div.zxlist li a\",\"imagestart\":\"<divclass=n_bd>\",\"imageend\":\"</div>\",\"imagediv\":\"div.introtxt img\",\"oninclude\":\"/admrw\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"GetImageFilter\",\"pagefilter\":\"\"},");
        //4. 哥哥嘿
        result.Append("{\"siteid\":\"4\",\"siterank\":\"A04\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"哥哥嘿【未更新】\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.1314hei.com\",\"sitelink\":\"http://www.1314hei.com/tupian/toupai/index.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"listdiv\":\"div.zxlist li a\",\"imagestart\":\"<divclass=temp23>\",\"imageend\":\"</div>\",\"imagediv\":\"div.introtxt img\",\"oninclude\":\"/tupian\",\"notinclude\":\"\",\"pagestart\":\"<atitle=\\\"Page\\\">\",\"pageend\":\"<br>\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //5. AV天堂网
        result.Append("{\"siteid\":\"5\",\"siterank\":\"A05\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"AV天堂网\",\"listpage\":\"list_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.avttavb.com\",\"sitelink\":\"http://www.avttavb.com/zipaitoupai/index.html\",\"liststart\":\"<divclass=\\\"newslist\\\">\",\"listend\":\"<divclass=\\\"page\\\">\",\"listdiv\":\"div.news_right li a\",\"imagestart\":\"<divid=\\\"text_novel\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div#text_novel img\",\"oninclude\":\"/zipaitoupai\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"SplitTitleFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //24. 夜夜嘿
        result.Append("{\"siteid\":\"24\",\"siterank\":\"A06\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"夜夜嘿【失效】\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://yeyehei.cc\",\"sitelink\":\"http://yeyehei.cc/pic/zipai/index.html\",\"liststart\":\"<divclass=\\\"idxnew\\\">\",\"listend\":\"</div>\",\"listdiv\":\"\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"\",\"oninclude\":\"/pic/zipai\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //9. 爱色阁-自拍专区
        result.Append("{\"siteid\":\"9\",\"siterank\":\"A07\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"爱色阁-自拍偷拍【失效】\",\"listpage\":\"list_8_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.woai00.com\",\"sitelink\":\"http://www.woai00.com/html/tpzp/list_8_1.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"listdiv\":\"table.listt td a\",\"imagestart\":\"<divclass=n_bd>\",\"imageend\":\"</div>\",\"imagediv\":\"div.content img\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //51. 爱色阁-自拍专区
        result.Append("{\"siteid\":\"51\",\"siterank\":\"A07\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"爱色阁-自拍偷拍\",\"listpage\":\"list_8_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.woai22.com\",\"sitelink\":\"http://www.woai22.com/html/tpzp/list_8_1.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"listdiv\":\"table.listt td a\",\"imagestart\":\"<divclass=n_bd>\",\"imageend\":\"</div>\",\"imagediv\":\"div.content img\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //27. 爱色阁-性爱自拍
        result.Append("{\"siteid\":\"27\",\"siterank\":\"A08\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"爱色阁-性爱自拍【失效】\",\"listpage\":\"index43_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.woai00.com\",\"sitelink\":\"http://www.woai00.com/html/part/index43.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"listdiv\":\"\",\"imagestart\":\"<divclass=content>\",\"imageend\":\"</div>\",\"imagediv\":\"\",\"oninclude\":\"/html/se\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //7. 91Porn-原创申请
        result.Append("{\"siteid\":\"7\",\"siterank\":\"A09\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"91Porn-原创申请\",\"listpage\":\"forumdisplay.php?fid=19&orderby=dateline&page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"https://91.t9m.space/\",\"sitelink\":\"https://91.t9m.space/forumdisplay.php?fid=19&orderby=dateline&page=1\",\"liststart\":\"<divid=\\\"threadlist\\\"\",\"listend\":\"</div>\",\"listdiv\":\"th.new a\",\"imagestart\":\"<divid=\\\"threadtitle\\\">\",\"imageend\":\"<divclass=\\\"postactions\\\">\",\"imagediv\":\"div.postmessage img\",\"oninclude\":\"viewthread\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoNumberFilter\",\"imagefilter\":\"GetImageFilter\",\"pagefilter\":\"\"},");
        //12. 91Porn-我爱我妻
        result.Append("{\"siteid\":\"12\",\"siterank\":\"A10\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"91Porn-我爱我妻\",\"listpage\":\"forumdisplay.php?fid=21&orderby=dateline&page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"https://91.t9m.space/\",\"sitelink\":\"https://91.t9m.space/forumdisplay.php?fid=21&orderby=dateline&page=1\",\"liststart\":\"<divid=\\\"threadlist\\\"\",\"listend\":\"</div>\",\"listdiv\":\"th.new a\",\"imagestart\":\"<divid=\\\"threadtitle\\\">\",\"imageend\":\"<divclass=\\\"postactions\\\">\",\"imagediv\":\"div.postmessage img\",\"oninclude\":\"viewthread\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoNumberFilter\",\"imagefilter\":\"GetImageFilter\",\"pagefilter\":\"\"},");
        //8. 超碰在线视频
        result.Append("{\"siteid\":\"8\",\"siterank\":\"A11\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"超碰在线视频\",\"listpage\":\"albums?page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://my.tv.de88.space\",\"sitelink\":\"http://my.tv.de88.space/albums?page=1\",\"liststart\":\"<divclass=\\\"blinkp\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"listdiv\":\"div.album_box_new a\",\"imagestart\":\"<divid=\\\"album\",\"imageend\":\"<divclass=\\\"pagination\\\">\",\"imagediv\":\"div.box img\",\"oninclude\":\"/album\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"pagination\\\">\",\"pageend\":\"</div>\",\"pagenext\":\"//?page=(*)\",\"pagediv\":\"div.pagination a\",\"pagelevel\":\"1\",\"listfilter\":\"GetTitleFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //22. 淫色淫色
        result.Append("{\"siteid\":\"22\",\"siterank\":\"A12\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"淫色淫色\",\"listpage\":\"index-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.myppp36.com\",\"sitelink\":\"http://www.myppp36.com/AAtupian/AAtb/zipai/index.html\",\"liststart\":\"<divclass=\\\"boxlistchannel\\\">\",\"listend\":\"</div>\",\"listdiv\":\"div.list li a\",\"imagestart\":\"<divclass=\\\"post-bd\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"\",\"oninclude\":\"/AAtupian\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoSpanFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //16. 精彩生活自拍汇
        result.Append("{\"siteid\":\"16\",\"siterank\":\"\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"精彩生活自拍汇【失效】\",\"listpage\":\"(*)\",\"pageencode\":\"gb2312\",\"domain\":\"http://bbs.we560.com/xtu/\",\"sitelink\":\"http://bbs.we560.com/xtu\",\"liststart\":\"<divalign=center>\",\"listend\":\"</div>\",\"listdiv\":\"\",\"imagestart\":\"<table\",\"imageend\":\"</div>\",\"imagediv\":\"\",\"oninclude\":\"html/\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //17. 正妹写真套图
        result.Append("{\"siteid\":\"17\",\"siterank\":\"\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"正妹写真套图【失效】\",\"listpage\":\"(*)\",\"pageencode\":\"gb2312\",\"domain\":\"http://bbs.we560.com/xz/cn\",\"sitelink\":\"http://bbs.we560.com/xz/cn\",\"liststart\":\"<divclass=\\\"viewbox\\\">\",\"listend\":\"</body>\",\"listdiv\":\"\",\"imagestart\":\"<divclass=\\\"img-show\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //23. Ady映画网
        result.Append("{\"siteid\":\"23\",\"siterank\":\"A13\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"Ady映画网\",\"listpage\":\"New(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://jj.ady1.info\",\"sitelink\":\"http://jj.ady1.info/zjgx/New.html\",\"liststart\":\"<divclass=\\\"pre_b\\\">\",\"listend\":\"<divclass=\\\"pre_b_class_page\\\">\",\"listdiv\":\"div.pre_b_classes_text h1 a\",\"imagestart\":\"<divclass=\\\"movie_c_pre\\\">\",\"imageend\":\"<divclass=\\\"movie_d\\\">\",\"imagediv\":\"div.movie_c_pre img\",\"oninclude\":\"/d\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //30. 东京干
        result.Append("{\"siteid\":\"30\",\"siterank\":\"A14\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"东京干【未更新】\",\"listpage\":\"sseexx60_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.av304.info\",\"sitelink\":\"http://www.av304.info/html/part/sseexx60.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"</div>\",\"listdiv\":\"table.listt td a\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.post-bd img\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //25. 久久热
        result.Append("{\"siteid\":\"25\",\"siterank\":\"A15\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"久久热\",\"listpage\":\"(*)/\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.99vv0.com\",\"sitelink\":\"http://www.99vv0.com/albums/\",\"liststart\":\"<divclass=\\\"thumbsmodels\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"listdiv\":\"div.thumb-content a\",\"imagestart\":\"<divclass=\\\"models-slider-big\\\">\",\"imageend\":\"<divclass=\\\"models-slider-small\\\">\",\"imagediv\":\"div.models-slider-big img\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"GetTitleFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //37. 久久热
        result.Append("{\"siteid\":\"37\",\"siterank\":\"A16\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"久久热论坛\",\"listpage\":\"forum-169-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.99rebbs6.com/\",\"sitelink\":\"http://www.99rebbs6.com/forum-169-1.html\",\"liststart\":\"<divid=\\\"threadlist\",\"listend\":\"<divid=\\\"filter_special_menu\",\"listdiv\":\"a.xst\",\"imagestart\":\"复制链接\",\"imageend\":\"<divid=\\\"p_btn\\\"\",\"imagediv\":\"div.t_fsz img\",\"oninclude\":\"thread\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //29. 色久久
        result.Append("{\"siteid\":\"29\",\"siterank\":\"A17\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"色久久【未更新】\",\"listpage\":\"index27_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.110pp.com\",\"sitelink\":\"http://www.110pp.com/html/part/index27.html\",\"liststart\":\"<divid=\\\"text\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"ul.textList li a\",\"imagestart\":\"<divclass=\\\"novelContent\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.novelContent img\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoSpanFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //32. 色色999
        result.Append("{\"siteid\":\"32\",\"siterank\":\"A18\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"色色999【快速】\",\"listpage\":\"23-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.1111kf.com\",\"sitelink\":\"http://www.1111kf.com/artlist/23.html\",\"liststart\":\"<divclass=\\\"atrlist\\\">\",\"listend\":\"</div>\",\"listdiv\":\"div.atrlist li a\",\"imagestart\":\"<divid=\\\"postmessage\\\"class=\\\"t_msgfont\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div#postmessage img\",\"oninclude\":\"/arts\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //33. 七次郎
        result.Append("{\"siteid\":\"33\",\"siterank\":\"A19\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"七次郎【超快】\",\"listpage\":\"index_page_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.qicifu.com\",\"sitelink\":\"http://www.qicifu.com/pictures/6/index.html\",\"liststart\":\"<divclass=\\\"list-video\\\">\",\"listend\":\"<ulclass=\\\"pagination\\\">\",\"listdiv\":\"div.img-cont a\",\"imagestart\":\"<divclass=\\\"ads_55\\\">\",\"imageend\":\"<divclass=\\\"end-list\\\">\",\"imagediv\":\"div.right img\",\"oninclude\":\"/picture\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"pagination\\\">\",\"pageend\":\"</ul>\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"GetTitleFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //2. 一焦进洞
        result.Append("{\"siteid\":\"2\",\"siterank\":\"A20\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"一焦进洞\",\"listpage\":\"(*).jsp\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.yjjdo.pw\",\"sitelink\":\"http://www.yjjdo.pw/yjj2/6/1.jsp\",\"liststart\":\"<divclass=\\\"mainArea\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"ul.textList li a\",\"imagestart\":\"<divclass=\\\"picContent\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.picContent img\",\"oninclude\":\"/yjj1\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoSpanFilter\",\"imagefilter\":\"GetImageFilter\",\"pagefilter\":\"\"},");
        //38. ♂爱AB♀
        result.Append("{\"siteid\":\"38\",\"siterank\":\"A21\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"♂爱AB♀【未更新】\",\"listpage\":\"list_10_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.iab06.com\",\"sitelink\":\"http://www.iab06.com/ws/list_10_1.html\",\"liststart\":\"<divclass=main>\",\"listend\":\"<divclass=dede_pages>\",\"listdiv\":\"ul.pic-list2 li a\",\"imagestart\":\"<divclass=\\\"article_body\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.article_body img\",\"oninclude\":\"/ws\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoImageFilter,NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //39. 撸撸嘿
        result.Append("{\"siteid\":\"39\",\"siterank\":\"A22\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"撸撸嘿\",\"listpage\":\"albums?page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.yehualu.ws\",\"sitelink\":\"http://www.yehualu.ws/albums?page=1\",\"liststart\":\"<divclass=\\\"container\\\">\",\"listend\":\"<divclass=\\\"list-group\\\">\",\"listdiv\":\"div.row div.well a\",\"imagestart\":\"<divclass=\\\"col-md-8\\\">\",\"imageend\":\"<divclass=\\\"footer-container\\\">\",\"imagediv\":\"div.row div.thumb-overlay img\",\"oninclude\":\"/album/\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"pagination\",\"pageend\":\"</ul>\",\"pagenext\":\"\",\"pagediv\":\"ul.pagination:first a\",\"pagelevel\":\"1\",\"listfilter\":\"NoImageFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //40. 开心五月
        result.Append("{\"siteid\":\"40\",\"siterank\":\"A23\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"开心五月【未更新】\",\"listpage\":\"index(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.pppcao8.com\",\"sitelink\":\"http://www.pppcao8.com/html/zt/index.html\",\"liststart\":\"<ulclass=\\\"textList\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"ul.textList li a\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.content img\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoSpanFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //42. 开心五月
        result.Append("{\"siteid\":\"42\",\"siterank\":\"A24\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"开心五月-综合图片【失效】\",\"listpage\":\"index16_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.pppcao8.com\",\"sitelink\":\"http://www.pppcao8.com/html/part/index16.html\",\"liststart\":\"<ulclass=\\\"textList\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"\",\"imagestart\":\"<divclass=\\\"novelContent\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //41. 银色网
        result.Append("{\"siteid\":\"41\",\"siterank\":\"A25\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"银色网\",\"listpage\":\"19_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.84kc.com\",\"sitelink\":\"http://www.84kc.com/html/part/19.html\",\"liststart\":\"<divclass=\\\"list\\\">\",\"listend\":\"<divclass=\\\"page\\\">\",\"listdiv\":\"table.listt td a\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"<liclass=\\\"last\\\">\",\"imagediv\":\"div.content img\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoFontFilter,NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //28. 就去路
        result.Append("{\"siteid\":\"28\",\"siterank\":\"A26\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"就去路\",\"listpage\":\"index(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.97luwang.com\",\"sitelink\":\"http://www.97luwang.com/tupian/wangyouzipai/index.html\",\"liststart\":\"<divclass=\\\"channel_list\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"div.flare li a\",\"imagestart\":\"<divclass=\\\"main_box\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.main_box img\",\"oninclude\":\"/tupian\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoEmFilter,NoSpanFilter,NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //6. 神马影院
        result.Append("{\"siteid\":\"6\",\"siterank\":\"A27\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"神马影院\",\"listpage\":\"index60_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.av301.info\",\"sitelink\":\"http://www.av301.info/nv/you/index60.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"</div>\",\"listdiv\":\"div.list td a\",\"imagestart\":\"<divclass=\\\"n_bd\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.content img\",\"oninclude\":\"/nv/so\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //43. 插插插
        result.Append("{\"siteid\":\"43\",\"siterank\":\"A28\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"插插插\",\"listpage\":\"list_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.872aa.com\",\"sitelink\":\"http://www.872aa.com/PIC01/index.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"listdiv\":\"div.zxlist li a\",\"imagestart\":\"<divclass=temp23>\",\"imageend\":\"</div>\",\"imagediv\":\"div.temp23 img\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //44. 奇米网
        result.Append("{\"siteid\":\"44\",\"siterank\":\"A29\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"奇米网【失效】\",\"listpage\":\"index(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.53ss.net\",\"sitelink\":\"http://www.53ss.net/it/dalutupian/index.html\",\"liststart\":\"<divclass=\\\"left\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"\",\"imagestart\":\"<divclass=\\\"up\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"\",\"oninclude\":\"/it/dalutupian\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //45. 色哥哥
        result.Append("{\"siteid\":\"45\",\"siterank\":\"A30\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"色哥哥\",\"listpage\":\"index32_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.sggqu.com\",\"sitelink\":\"http://www.sggqu.com/html/part/index32.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"listdiv\":\"div.zxlist li a\",\"imagestart\":\"<divclass=\\\"biaoti\\\">\",\"imageend\":\"<divclass=\\\"pagea\\\">\",\"imagediv\":\"div.newsdes img\",\"oninclude\":\"/html/article\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //46. 66爱爱
        result.Append("{\"siteid\":\"46\",\"siterank\":\"A31\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"66爱爱\",\"listpage\":\"9_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.40gege.com\",\"sitelink\":\"http://www.40gege.com/news/other/9.html\",\"liststart\":\"<ulclass=\\\"article-list\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"ul.article-list li a\",\"imagestart\":\"<divclass=\\\"c\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.show img\",\"oninclude\":\"/news/class\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoFontFilter,NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //47. 草榴社区
        result.Append("{\"siteid\":\"47\",\"siterank\":\"A32\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"草榴社区【失效】\",\"listpage\":\"thread0806.php?fid=16&search=&page=(*)\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.secduu.com/\",\"sitelink\":\"http://www.secduu.com/thread0806.php?fid=16&search=&page=1\",\"liststart\":\"id=\\\"ajaxtable\\\"\",\"listend\":\"<table\",\"listdiv\":\"\",\"imagestart\":\"<divclass=\\\"tpc_content\",\"imageend\":\"<table\",\"imagediv\":\"\",\"oninclude\":\"htm_data\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //48. 台湾妹中文网
        result.Append("{\"siteid\":\"48\",\"siterank\":\"A33\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"台湾妹中文网\",\"listpage\":\"list5(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.42xd.com\",\"sitelink\":\"http://www.42xd.com/tupianqu/TSE/list51.html\",\"liststart\":\"<divid=\\\"text\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"div.list li a\",\"imagestart\":\"<divclass=\\\"post\\\">\",\"imageend\":\"<divclass=\\\"newpagination\\\">\",\"imagediv\":\"div.post img\",\"oninclude\":\"/tttppp\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"newpagination\\\">\",\"pageend\":\"</div>\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoSpanFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //49. 自拍社
        result.Append("{\"siteid\":\"49\",\"siterank\":\"A34\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"自拍社【失效】\",\"listpage\":\"/(*)\",\"pageencode\":\"utf-8\",\"domain\":\"https://www.zipaishe.com\",\"sitelink\":\"https://www.zipaishe.com/page/1\",\"liststart\":\"<sectionclass=\\\"maincontainer\\\">\",\"listend\":\"</section>\",\"listdiv\":\"\",\"imagestart\":\"<article>\",\"imageend\":\"</article>\",\"imagediv\":\"\",\"oninclude\":\"/gallery\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"bpages\\\">\",\"pageend\":\"</div>\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //50. 良心撸
        result.Append("{\"siteid\":\"50\",\"siterank\":\"A35\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"良心撸\",\"listpage\":\"(*).htm\",\"pageencode\":\"utf-8\",\"domain\":\"https://www.mumu62.com\",\"sitelink\":\"https://www.mumu62.com/htm/piclist1/1.htm\",\"liststart\":\"<ulclass=\\\"textList\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"ul.textList li a\",\"imagestart\":\"<divclass=\\\"picContent\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.picContent img\",\"oninclude\":\"/htm\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //51. 去撸撸吧
        result.Append("{\"siteid\":\"51\",\"siterank\":\"A36\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"去撸撸吧\",\"listpage\":\"index(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.qululu8.com\",\"sitelink\":\"http://www.qululu8.com/tupian/wangyouzipai/index.html\",\"liststart\":\"\",\"listend\":\"\",\"listdiv\":\"div.flare li a\",\"imagestart\":\"\",\"imageend\":\"\",\"imagediv\":\"div.main_box img\",\"oninclude\":\"/tupian\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoEmFilter,NoSpanFilter,NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //52. 777jk
        result.Append("{\"siteid\":\"52\",\"siterank\":\"A37\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"777jk\",\"listpage\":\"wqubi_6_(*).asp\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.777jk.pw\",\"sitelink\":\"http://www.777jk.pw/wqubi_6.asp\",\"liststart\":\"\",\"listend\":\"\",\"listdiv\":\"div.listbox li a\",\"imagestart\":\"\",\"imageend\":\"\",\"imagediv\":\"div.content img\",\"oninclude\":\"\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"NoSpanFilter\",\"imagefilter\":\"GetImageFilter\",\"pagefilter\":\"\"},");

        ////////////////////////////////////////////////////////////////////////////VIP分隔线////////////////////////////////////////////////////////////////////////////

        //31. 中国人体艺术
        result.Append("{\"siteid\":\"31\",\"siterank\":\"B01\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"中国人体艺术\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"https://www.rt114.net\",\"sitelink\":\"https://www.rt114.net/zg/index.html\",\"liststart\":\"<ulclass=\\\"list-inline\",\"listend\":\"</ul>\",\"listdiv\":\"li.thumbnail a\",\"imagestart\":\"<divclass=\\\"picbox\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.thumbnail img\",\"oninclude\":\"https://www.rt114.net/html\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"page\\\">\",\"pageend\":\"...\",\"pagenext\":\"page_(*)\",\"pagediv\":\"ul.pagination a\",\"pagelevel\":\"2\",\"listfilter\":\"GetTitleFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //21. 人体艺术
        result.Append("{\"siteid\":\"21\",\"siterank\":\"B02\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"人体艺术\",\"listpage\":\"(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.rentiyishu77.com/rentiwaipai/\",\"sitelink\":\"http://www.rentiyishu77.com/rentiwaipai/index.html\",\"liststart\":\"<divclass=\\\"lm\\\">\",\"listend\":\"<ulclass=\\\"page\\\"\",\"listdiv\":\"ul.photo li a\",\"imagestart\":\"<ulclass=\\\"file\\\">\",\"imageend\":\"</ul>\",\"imagediv\":\"ul.file img\",\"oninclude\":\"20\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"photo\",\"pageend\":\"</ul>\",\"pagenext\":\"page_(*)\",\"pagediv\":\"ul.photo a\",\"pagelevel\":\"1\",\"listfilter\":\"NoImageFilter,NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //13. 妹子图
        result.Append("{\"siteid\":\"13\",\"siterank\":\"B03\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"妹子图【超快】\",\"listpage\":\"(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.mzitu.com\",\"sitelink\":\"http://www.mzitu.com/page/1\",\"liststart\":\"<divclass=\\\"postlist\",\"listend\":\"</ul>\",\"listdiv\":\"div.postlist li a\",\"imagestart\":\"<divclass=\\\"main-image\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.main-image img\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"pagenavi\",\"pageend\":\"</div>\",\"pagenext\":\"/(*)\",\"pagediv\":\"div.pagenavi a\",\"pagelevel\":\"2\",\"listfilter\":\"GetTitleFilter\",\"imagefilter\":\"\",\"pagefilter\":\"GetSpanFilter\"},");
        //14. 猫扑炫图
        result.Append("{\"siteid\":\"14\",\"siterank\":\"B04\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"猫扑炫图\",\"listpage\":\"list_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://tt.mop.com\",\"sitelink\":\"http://tt.mop.com/xuan/list_1.html\",\"liststart\":\"<divclass=\\\"main\",\"listend\":\"<divclass=\\\"page\",\"listdiv\":\"div.picTitle a\",\"imagestart\":\"<divclass=\\\"txtmod\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.txtmod img\",\"oninclude\":\"http://tt\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //15. ZOL人像摄影
        result.Append("{\"siteid\":\"15\",\"siterank\":\"B05\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"ZOL人像摄影\",\"listpage\":\"d16_pic_new_p(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://bbs.zol.com.cn\",\"sitelink\":\"http://bbs.zol.com.cn/dcbbs/d16_pic_new_p1.html\",\"liststart\":\"id=\\\"picBookList\\\"\",\"listend\":\"</ul>\",\"listdiv\":\"div.pic-infor h4 a\",\"imagestart\":\"<divid=\\\"bookContent\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div#bookContent img\",\"oninclude\":\"/dcbbs\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"GetImageFilter\",\"pagefilter\":\"\"},");
        //10. 1000人体
        result.Append("{\"siteid\":\"10\",\"siterank\":\"B06\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"1000人体\",\"listpage\":\"list_1_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.renti1000.com\",\"sitelink\":\"http://www.renti1000.com/yazhourenti/index.html\",\"liststart\":\"<ulclass=\\\"product01\\\">\",\"listend\":\"</ul>\",\"listdiv\":\"a.pic\",\"imagestart\":\"<divclass=\\\"big_img\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.big_img img\",\"oninclude\":\"/yazhourenti\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"pagelist\\\">\",\"pageend\":\"</ul>\",\"pagenext\":\"\",\"pagediv\":\"ul.pagelist a\",\"pagelevel\":\"1\",\"listfilter\":\"NoImageFilter,NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //11. 人体艺术
        result.Append("{\"siteid\":\"11\",\"siterank\":\"\",\"viplevel\":\"2\",\"ishided\":\"1\",\"sitename\":\"人体艺术【失效】\",\"listpage\":\"list_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.68s.net\",\"sitelink\":\"http://www.68s.net/list/zhongguorenti/list_1.html\",\"liststart\":\"<divclass=\\\"list\\\">\",\"listend\":\"<divclass=\\\"pages\\\">\",\"listdiv\":\"\",\"imagestart\":\"<divclass=\\\"imgbox\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div.big_img img\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"pages\\\">\",\"pageend\":\"</div>\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //18. 黑丝网
        result.Append("{\"siteid\":\"18\",\"siterank\":\"\",\"viplevel\":\"3\",\"ishided\":\"1\",\"sitename\":\"黑丝网【失效】\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.heisiwang.com\",\"sitelink\":\"http://www.heisiwang.com/xinggan/index.html\",\"liststart\":\"<divclass=\\\"channel-ctn\\\">\",\"listend\":\"<divclass=\\\"pages\\\">\",\"listdiv\":\"\",\"imagestart\":\"<divclass=\\\"endtext\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"\",\"oninclude\":\"/pic\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //19. 爱人体
        result.Append("{\"siteid\":\"19\",\"siterank\":\"B07\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"爱人体\",\"listpage\":\"(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.airenti99.com/yazhourenti/\",\"sitelink\":\"http://www.airenti99.com/yazhourenti/index.html\",\"liststart\":\"<divclass=\\\"lm\\\">\",\"listend\":\"<ulclass=\\\"page\\\"\",\"listdiv\":\"ul.photo li a\",\"imagestart\":\"<ulclass=\\\"file\\\">\",\"imageend\":\"</ul>\",\"imagediv\":\"ul.file img\",\"oninclude\":\"20\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"photo\",\"pageend\":\"</ul>\",\"pagenext\":\"page_(*)\",\"pagediv\":\"ul.photo a\",\"pagelevel\":\"1\",\"listfilter\":\"NoImageFilter,NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //20. 漂漂美术馆
        result.Append("{\"siteid\":\"20\",\"siterank\":\"B08\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"漂漂美术馆\",\"listpage\":\"(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.ppmsg.net/jiepaimeinv/\",\"sitelink\":\"http://www.ppmsg.net/jiepaimeinv/index.html\",\"liststart\":\"<divclass=\\\"lm\\\">\",\"listend\":\"<ulclass=\\\"page\\\"\",\"listdiv\":\"ul.image li a\",\"imagestart\":\"<divid=\\\"imagelist\\\">\",\"imageend\":\"</div>\",\"imagediv\":\"div#imagelist img\",\"oninclude\":\"20\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"image\\\">\",\"pageend\":\"</ul>\",\"pagenext\":\"page_(*)\",\"pagediv\":\"ul.image a\",\"pagelevel\":\"1\",\"listfilter\":\"NoImageFilter,NoHtmlFilter\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //34. 福利图片
        result.Append("{\"siteid\":\"34\",\"siterank\":\"B09\",\"viplevel\":\"3\",\"ishided\":\"1\",\"sitename\":\"福利图片【失效】\",\"listpage\":\"page/(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.dongde.in\",\"sitelink\":\"http://www.dongde.in/category/福利图片/\",\"liststart\":\"<divclass=\\\"content\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"listdiv\":\"\",\"imagestart\":\"<articleclass=\\\"article-content\\\">\",\"imageend\":\"</article>\",\"imagediv\":\"\",\"oninclude\":\"http://dongde.in/post\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //35. 街拍美女
        result.Append("{\"siteid\":\"35\",\"siterank\":\"B10\",\"viplevel\":\"3\",\"ishided\":\"1\",\"sitename\":\"街拍美女【失效】\",\"listpage\":\"page/(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.dongde.in\",\"sitelink\":\"http://www.dongde.in/category/街拍美女/\",\"liststart\":\"<divclass=\\\"content\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"listdiv\":\"\",\"imagestart\":\"<articleclass=\\\"article-content\\\">\",\"imageend\":\"</article>\",\"imagediv\":\"\",\"oninclude\":\"http://dongde.in/post\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"},");
        //36. 爱色阁-街拍图区
        result.Append("{\"siteid\":\"36\",\"siterank\":\"B11\",\"viplevel\":\"3\",\"ishided\":\"1\",\"sitename\":\"爱色阁-街拍图区【失效】\",\"listpage\":\"list_9_(*).html\",\"pageencode\":\"gb2312\",\"domain\":\"http://www.woai00.com\",\"sitelink\":\"http://www.woai00.com/html/cqmm/list_9_1.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"listdiv\":\"\",\"imagestart\":\"<divclass=content>\",\"imageend\":\"</div>\",\"imagediv\":\"\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\":\"\",\"pagenext\":\"\",\"pagediv\":\"\",\"pagelevel\":\"0\",\"listfilter\":\"\",\"imagefilter\":\"\",\"pagefilter\":\"\"}");
        //end
        result.Append("],");

        //外部词典
        result.Append("\"ext_dic\":[\"内射\",\"內射\",\"车震\",\"大屁股\",\"人妻\",\"美臀\",\"肥臀\",\"翘臀\",\"换妻\",\"后入\",\"後入\",\"豐滿\",\"水多\",\"炮友\",\"網友\",\"白漿\",\"闺蜜\",\"陰道\",\"少婦\",\"熟婦\",\"賓館\",\"鮑魚\",\"極品\",\"鄰居\"],");

        //停止词典
        result.Append("\"stop_dic\":[\"的\",\"了\",\"在\",\"是\",\"我\",\"有\",\"和\",\"就\",\"不\",\"人\",\"都\",\"一\",\"一个\",\"上\",\"也\",\"很\",\"到\",\"说\",\"要\",\"去\",\"你\",\"会\",\"着\",\"没有\",\"看\",\"好\",\"自己\",\"这\"],");

        //删除词典
        result.Append("\"del_dic\":[\"-自拍偷拍\",\"達蓋爾先鋒團\",\"榮譽出品\",\"達蓋爾的旗幟\",\"原创投稿\",\"原創投稿\",\"游客投稿\",\"图吧水印\",\"自拍活动\",\"流精典藏-\",\"原创认证\",\"原创验证\",\"原创手势认证\",\"原创手势验证\",\"原创ID认证\",\"原创ID验证\",\"必须收藏的瑕疵影像！\"]}");

        Response.Write(result.ToString());
        Response.End();
    }
}