//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AALifeDbContext : DbContext
    {
        public AALifeDbContext()
            : base("name=AALifeDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardTable> CardTable { get; set; }
        public virtual DbSet<ItemTable> ItemTable { get; set; }
        public virtual DbSet<ItemTypeTable> ItemTypeTable { get; set; }
        public virtual DbSet<OAuthTable> OAuthTable { get; set; }
        public virtual DbSet<UserFromTable> UserFromTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
        public virtual DbSet<WorkDayTable> WorkDayTable { get; set; }
        public virtual DbSet<ZhuanTiTable> ZhuanTiTable { get; set; }
        public virtual DbSet<ZhuanZhangTable> ZhuanZhangTable { get; set; }
        public virtual DbSet<CategoryTypeTable> CategoryTypeTable { get; set; }
        public virtual DbSet<UserCategoryTable> UserCategoryTable { get; set; }
        public virtual DbSet<RegionTypeTable> RegionTypeTable { get; set; }
    }
}
