//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTableView2019
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public int CategoryTypeID { get; set; }
        public decimal ItemPrice { get; set; }
        public System.DateTime ItemBuyDate { get; set; }
        public int UserID { get; set; }
        public byte Recommend { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public byte Synchronize { get; set; }
        public string RegionType { get; set; }
        public string ItemType { get; set; }
        public Nullable<int> ZhuanTiID { get; set; }
        public int CardID { get; set; }
        public string Remark { get; set; }
        public string CategoryTypeName { get; set; }
        public string ItemTypeName { get; set; }
        public string UserName { get; set; }
        public string CardName { get; set; }
        public string ZhuanTiName { get; set; }
    }
}
