//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuthTable
    {
        public int OAuthID { get; set; }
        public string OpenID { get; set; }
        public string AccessToken { get; set; }
        public int UserID { get; set; }
        public int OldUserID { get; set; }
        public byte OAuthBound { get; set; }
        public string OAuthFrom { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
