//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionTypeTable
    {
        public string RegionType { get; set; }
        public string RegionTypeName { get; set; }
        public string RegionTypeSymbol { get; set; }
        public byte Rank { get; set; }
    }
}
