//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTableView
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserNickName { get; set; }
        public string UserImage { get; set; }
        public string UserPhone { get; set; }
        public string UserEmail { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserTheme { get; set; }
        public string UserWorkDay { get; set; }
        public string UserFrom { get; set; }
        public byte Synchronize { get; set; }
        public string UserFromName { get; set; }
        public string WorkDayName { get; set; }
        public string UserThemeName { get; set; }
    }
}
