//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.CardTable = new HashSet<CardTable>();
            this.ItemTable = new HashSet<ItemTable>();
            this.OAuthTable = new HashSet<OAuthTable>();
            this.ZhuanTiTable = new HashSet<ZhuanTiTable>();
            this.ZhuanZhangTable = new HashSet<ZhuanZhangTable>();
            this.UserCategoryTable = new HashSet<UserCategoryTable>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserNickName { get; set; }
        public string UserImage { get; set; }
        public string UserPhone { get; set; }
        public string UserEmail { get; set; }
        public string UserTheme { get; set; }
        public byte UserLevel { get; set; }
        public string UserFrom { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserCity { get; set; }
        public decimal UserMoney { get; set; }
        public string UserWorkDay { get; set; }
        public string UserFunction { get; set; }
        public int CategoryRate { get; set; }
        public byte Synchronize { get; set; }
        public Nullable<decimal> MoneyStart { get; set; }
        public Nullable<byte> IsUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardTable> CardTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemTable> ItemTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OAuthTable> OAuthTable { get; set; }
        public virtual UserFromTable UserFromTable { get; set; }
        public virtual WorkDayTable WorkDayTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZhuanTiTable> ZhuanTiTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZhuanZhangTable> ZhuanZhangTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCategoryTable> UserCategoryTable { get; set; }
    }
}
