//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPageTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ViewPageTable()
        {
            this.ViewTable = new HashSet<ViewTable>();
        }
    
        public int PageID { get; set; }
        public string PageName { get; set; }
        public string PageTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViewTable> ViewTable { get; set; }
    }
}
