//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AALife.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZhuanZhangTable
    {
        public int ZhuanZhangID { get; set; }
        public int ZhuanZhangFrom { get; set; }
        public int ZhuanZhangTo { get; set; }
        public System.DateTime ZhuanZhangDate { get; set; }
        public decimal ZhuanZhangMoney { get; set; }
        public byte Synchronize { get; set; }
        public byte ZhuanZhangLive { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int UserID { get; set; }
        public string ZhuanZhangNote { get; set; }
        public Nullable<int> ZZID { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
