//常量
$.const = {
    default: {
        BgImg: "/images/bg/bg.jpg",
        UserImg: "/images/user/user.gif",
        PageButton: 10,
        PageNumber: 30,
        PageNumbers: [10, 30, 50, 100],
        TrueFalse: [{ Name: "是", Value: "1" }, { Name: "否", Value: "0" }]
    },
    webapi: {
        items: "/api/v1/itemsapi",
        itemnames: "/api/v1/itemnamesapi/{0}",
        users: "/api/v1/usersapi",
        userselects: "/api/v1/userselectsapi",
        usersselect: "/api/v1/usersselectapi",
        usernames: "/api/v1/usernamesapi",
        roles: "/api/v1/rolesapi",
        rolesuser: "/api/v1/rolesuserapi",
        rolesuser_id: "/api/v1/rolesuserapi/{0}",
        rolestree: "/api/v1/rolestreeapi",
        permissions: "/api/v1/permissionsapi",
        permissionsroleupdate: "/api/v1/permissionsroleupdateapi",
        permissionsdeptmentupdate: "/api/v1/permissionsdeptmentupdateapi",
        permissionspositionupdate: "/api/v1/permissionspositionupdateapi",
        parameters: "/api/v1/parametersapi",
        parameters_id: "/api/v1/parametersapi/{0}",
        parameterstree: "/api/v1/parameterstreeapi",
        paramsbyname: "/api/v1/paramsbynameapi/{0}",
        userroles: "/api/v1/userrolesapi/{0}",
        userroleselects: "/api/v1/userroleselectsapi/{0}",
        userdeptments: "/api/v1/userdeptmentsapi/{0}",
        categorytypes: "/api/v1/categorytypesapi/{0}",
        zhuantis: "/api/v1/zhuantisapi/{0}",
        zhuanzhangs: "/api/v1/zhuanzhangsapi/{0}",
        cards: "/api/v1/cardsapi/{0}",
        messagetemplates: "/api/v1/messagetemplatesapi",
        scheduletasks: "/api/v1/scheduletasksapi",
        deptments: "/api/v1/deptmentsapi",
        deptmentsuser: "/api/v1/deptmentsuserapi",
        deptmentsuser_id: "/api/v1/deptmentsuserapi/{0}",
        deptmentstree: "/api/v1/deptmentstreeapi",
        deptmentstree_id: "/api/v1/deptmentstreeapi/{0}",
        deptmentsposition: "/api/v1/deptmentspositionapi",
        deptmentsposition_id: "/api/v1/deptmentspositionapi/{0}",
        positions: "/api/v1/positionsapi",
        positionstree: "/api/v1/positionstreeapi",
        positionstree_id: "/api/v1/positionstreeapi/{0}",
        positionsuser: "/api/v1/positionsuserapi",
        positionsuser_id: "/api/v1/positionsuserapi/{0}"
    },
    pages: {
        category: "/User/CategoryPage",
        card: "/User/CardPage",
        zhuanti: "/User/ZhuanTiPage",
        zhuanzhang: "/User/ZhuanZhangPage"
    }
};
