//常量
$.const = {
    default: {
        BgImg: "/images/bg/bg.jpg",
        UserImg: "/images/user/user.gif",
        PageButton: 10,
        PageNumber: 30,
        PageNumbers: [10, 30, 50, 100],
        TrueFalse: [{ Name: "是", Value: "1" }, { Name: "否", Value: "0" }]
    },
    webapi: {
        items: "/api/v1/itemsapi",
        itemnames: "/api/v1/itemnamesapi?id={0}",
        users: "/api/v1/usersapi",
        userselects: "/api/v1/userselectsapi",
        usersselect: "/api/v1/usersselectapi",
        deptmentsuserselect: "/api/v1/deptmentsuserselectapi",
        usernames: "/api/v1/usernamesapi",
        roles: "/api/v1/rolesapi",
        rolesuser: "/api/v1/rolesuserapi",
        rolesuser_id: "/api/v1/rolesuserapi?id={0}",
        rolestree: "/api/v1/rolestreeapi",
        permissions: "/api/v1/permissionsapi",
        permissionsroleupdate: "/api/v1/permissionsroleupdateapi",
        permissionsdeptmentupdate: "/api/v1/permissionsdeptmentupdateapi",
        permissionspositionupdate: "/api/v1/permissionspositionupdateapi",
        parameters: "/api/v1/parametersapi",
        parameters_id: "/api/v1/parametersapi?id={0}",
        parameterstree: "/api/v1/parameterstreeapi",
        paramsbyname: "/api/v1/paramsbynameapi?id={0}",
        usersrole_id: "/api/v1/userrolesapi?id={0}",
        userroleselects: "/api/v1/userroleselectsapi?id={0}",
        userdeptments: "/api/v1/userdeptmentsapi?id={0}",
        usersdeptment: "/api/v1/usersdeptmentapi",
        usersdeptment_id: "/api/v1/usersdeptmentapi?id={0}",
        usersposition: "/api/v1/userspositionapi",
        usersposition_id: "/api/v1/userspositionapi?id={0}",
        categorytypes: "/api/v1/categorytypesapi?id={0}",
        zhuantis: "/api/v1/zhuantisapi?id={0}",
        zhuanzhangs: "/api/v1/zhuanzhangsapi?id={0}",
        cards: "/api/v1/cardsapi?id={0}",
        messagetemplates: "/api/v1/messagetemplatesapi",
        scheduletasks: "/api/v1/scheduletasksapi",
        deptment: "/api/v1/deptmentapi",
        deptment_id: "/api/v1/deptmentapi?id={0}",
        deptmentsuser: "/api/v1/deptmentsuserapi",
        deptmentsuser_id: "/api/v1/deptmentsuserapi?id={0}",
        deptmentspositionuser: "/api/v1/deptmentspositionuserapi",
        deptmentspositionuser_id: "/api/v1/deptmentspositionuserapi?id={0}",
        deptmentstree: "/api/v1/deptmentstreeapi",
        deptmentstree_id: "/api/v1/deptmentstreeapi?id={0}",
        deptments: "/api/v1/deptmentsapi",
        deptments_id: "/api/v1/deptmentsapi?id={0}",
        deptmentspositiontree: "/api/v1/deptmentspositiontreeapi",
        deptmentspositiontree_id: "/api/v1/deptmentspositiontreeapi?id={0}",
        deptmentspositiontreelist: "/api/v1/deptmentspositiontreelistapi",
        deptmentspositiontreelist_id: "/api/v1/deptmentspositiontreelistapi?id={0}",
        deptmentsposition: "/api/v1/deptmentspositionapi",
        deptmentsposition_id: "/api/v1/deptmentspositionapi?id={0}",
        positions: "/api/v1/positionsapi",
        positions_id: "/api/v1/positionsapi?id={0}",
        positionstree: "/api/v1/positionstreeapi",
        positionstree_id: "/api/v1/positionstreeapi?id={0}",
        positionsdeptmenttree: "/api/v1/positionsdeptmenttreeapi",
        positionsdeptmenttree_id: "/api/v1/positionsdeptmenttreeapi?id={0}",
        positionsuser: "/api/v1/positionsuserapi",
        positionsuser_id: "/api/v1/positionsuserapi?id={0}",
        positionsusertree: "/api/v1/positionsusertreeapi",
        positionsusertree_id: "/api/v1/positionsusertreeapi?id={0}"
    },
    pages: {
        category: "/User/CategoryPage",
        card: "/User/CardPage",
        zhuanti: "/User/ZhuanTiPage",
        zhuanzhang: "/User/ZhuanZhangPage"
    }
};
